[package]
name = "hypersearch_codegen"
version = "0.1.0"
edition = "2021"
description = "Macro library for hypersearch"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
