[package]
name = "hypersearch_codegen"
version = "0.2.1"
edition = "2021"
description = "Macro library for hypersearch"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0.92", features=["full"]}
quote = "1.0.18"
proc-macro2 = "1.0.37"